# Requires REST Client extension

@host=https://localhost:7183

GET {{host}}/truck/health

###
GET {{host}}/truck/dev007


###
POST {{host}}/truck
content-type: application/json

{
    "code": "dev007",
    "name": "yellow truck"
}