# Requires REST Client extension

@host=https://localhost:7183

GET {{host}}/truck/health

###
GET {{host}}/truck/dev018

###
PUT {{host}}/truck
content-type: application/json

{
    "TruckCode": "dev018",
    "TruckName": "red truck",
    "TruckStatus": "ToJob",
    "TruckDescription": "Very good vechicle"
}

### Bad Request
PUT {{host}}/truck
content-type: application/json

{
    "TruckCode": "dev007_1111111111",
    "TruckName": null,
    "TruckStatus": "uknownStatus"
}